version: '3.8'
services:
  kordi-db-compose:
    container_name: kordi-db-compose
    image: mysql:8.0.27
    ports:
      - 3306:3306
    restart: unless-stopped
    environment:
      MYSQL_USER: kordi
      MYSQL_PASSWORD: kordi
      MYSQL_DATABASE: kordi
      MYSQL_ROOT_PASSWORD: kordi
    volumes:
      - db:/var/lib/
  kordi-maildev-compose:
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
  kordi-server-compose:
    restart: on-failure
    depends_on:
      - kordi-db-compose
    container_name: kordi-server-compose
    build: ../
    image: kordi:latest
    ports:
      - 8081:8080
    environment:
      - DB_HOSTNAME=kordi-db-compose
      - DB_PORT=3306
      - DB_NAME=kordi
      - DB_USER=kordi
      - DB_PASS=kordi
      - MAIL_HOST=kordi-maildev-compose
      - MAIL_PORT=1025
      - MAIL_USER=kordi
      - MAIL_PASSWORD=kordi
      - TWILIO_ACCOUNT_SID=xxx
      - TWILIO_AUTH_TOKEN=xxx
      - TWILIO_SERVICE_ID=xxx
      - ALLOWED_ORIGINS=http://localhost:4200,http://localhost:4300
volumes:
  db: